# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: banks.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\x12\x04\x62\x61nk\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x01\n\x12TransactionRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x11\n\toperation\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x11\n\tbranch_id\x18\x04 \x01(\x05\x12\x10\n\x08write_id\x18\x05 \x01(\x05\x12&\n\twrite_set\x18\x06 \x03(\x0b\x32\x13.bank.WriteSetEntry\"6\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\"5\n\rWriteSetEntry\x12\x11\n\tbranch_id\x18\x01 \x01(\x05\x12\x11\n\twrite_ids\x18\x02 \x03(\x05\"#\n\x0fWriteIDResponse\x12\x10\n\x08write_id\x18\x01 \x01(\x05\x32\x87\x01\n\x04\x42\x61nk\x12\x42\n\x0bMsgDelivery\x12\x18.bank.TransactionRequest\x1a\x19.bank.TransactionResponse\x12;\n\nGetWriteID\x12\x16.google.protobuf.Empty\x1a\x15.bank.WriteIDResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONREQUEST']._serialized_start=51
  _globals['_TRANSACTIONREQUEST']._serialized_end=204
  _globals['_TRANSACTIONRESPONSE']._serialized_start=206
  _globals['_TRANSACTIONRESPONSE']._serialized_end=260
  _globals['_WRITESETENTRY']._serialized_start=262
  _globals['_WRITESETENTRY']._serialized_end=315
  _globals['_WRITEIDRESPONSE']._serialized_start=317
  _globals['_WRITEIDRESPONSE']._serialized_end=352
  _globals['_BANK']._serialized_start=355
  _globals['_BANK']._serialized_end=490
# @@protoc_insertion_point(module_scope)
